name: C++ CMake CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-latest

    steps:
     
    - uses: actions/checkout@v3
      with:
        submodules: recursive
        
    - uses: openrndr/setup-opengl@v1.1

    - name: Apt update
      run: sudo apt-get update

    - name: Install Ninja
      run: sudo apt-get install -y ninja-build

    - name: Install OpenGL
      run: sudo apt-get install -y libgl1-mesa-dev libxrandr-dev libx11-dev libxinerama-dev libxcursor-dev libxi-dev

    - name: Install Assimp
      run: sudo apt-get install -y libassimp-dev libassimp5

    - name: Install OpenAL
      run: sudo apt-get install -y libopenal-dev libopenal1
        
    - name: Configure CMake
      run: cmake -G Ninja -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
